# Generated by Django 5.2.8 on 2026-07-06 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dividendo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('fecha_corte', models.DateField(verbose_name='Fecha de corte')),
                ('fecha_pago', models.DateField(verbose_name='Fecha de pago')),
                ('monto', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Monto')),
                ('moneda', models.CharField(choices=[('CLP', 'Peso Chileno'), ('USD', 'Dólar Estadounidense'), ('EUR', 'Euro')], default='CLP', max_length=3, verbose_name='Moneda')),
                ('tipo_dividendo', models.CharField(choices=[('ORDINARIO', 'Ordinario'), ('EXTRAORDINARIO', 'Extraordinario')], default='ORDINARIO', max_length=20, verbose_name='Tipo de dividendo')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=10, verbose_name='Estado')),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dividendos', to='tributario.instrumento', verbose_name='Instrumento')),
            ],
            options={
                'verbose_name': 'Dividendo',
                'verbose_name_plural': 'Dividendos',
                'db_table': 'dividendos',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
