# Generated by Django 5.2.8 on 2026-07-06 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('ticker', models.CharField(max_length=20, unique=True, verbose_name='Ticker')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('isin', models.CharField(max_length=20, unique=True, verbose_name='ISIN')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=10)),
                ('mercado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instrumentos', to='tributario.mercado', verbose_name='Mercado')),
            ],
            options={
                'verbose_name': 'Instrumento',
                'verbose_name_plural': 'Instrumentos',
                'db_table': 'instrumentos',
                'ordering': ['ticker'],
            },
        ),
    ]
