# Generated by Django 5.2.8 on 2026-07-06 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributario', '0002_instrumento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrumento',
            options={'ordering': ['ticker']},
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='isin',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='mercado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instrumentos', to='tributario.mercado'),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='ticker',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
