# Generated by Django 5.2.8 on 2026-07-06 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributario', '0002_dividendo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionTributaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('ejercicio', models.PositiveIntegerField(verbose_name='Ejercicio')),
                ('numero_evento', models.PositiveIntegerField(verbose_name='Número de Evento')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('isfut', models.BooleanField(default=False, verbose_name='¿Es ISFUT?')),
                ('factor_actualizacion', models.DecimalField(decimal_places=8, max_digits=12, verbose_name='Factor de Actualización')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=10, verbose_name='Estado')),
                ('dividendo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to='tributario.dividendo', verbose_name='Dividendo')),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to='tributario.instrumento', verbose_name='Instrumento')),
            ],
            options={
                'verbose_name': 'Calificación Tributaria',
                'verbose_name_plural': 'Calificaciones Tributarias',
                'db_table': 'calificaciones_tributarias',
                'ordering': ['-ejercicio', 'numero_evento'],
                'constraints': [models.UniqueConstraint(fields=('instrumento', 'ejercicio', 'numero_evento'), name='uq_calificacion_instrumento_ejercicio_evento')],
            },
        ),
    ]
