# Generated by Django 5.2.8 on 2026-07-06 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributario', '0003_alter_instrumento_options_alter_instrumento_isin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrumento',
            options={'ordering': ['ticker'], 'verbose_name': 'Instrumento', 'verbose_name_plural': 'Instrumentos'},
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='isin',
            field=models.CharField(max_length=20, unique=True, verbose_name='ISIN'),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='mercado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instrumentos', to='tributario.mercado', verbose_name='Mercado'),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='ticker',
            field=models.CharField(max_length=20, unique=True, verbose_name='Ticker'),
        ),
    ]
